services:
  - type: web
    name: ikea-matcher-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_service.py
    envVars:
      - key: FLASK_ENV
        value: production
