services:
  - type: web
    name: furniture-matcher-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_service.py
    envVars:
      - key: FLASK_ENV
        value: production
